data_path: "../data/member_strengths.csv"
user_num: &user_num 200 # 適当に大きい数字にしておくと全社員になる
strength_num: &strength_num 5
name_list: &name_list null # Noneはyamlではnull
# num_iter: 20000
num_iter: 6000
save_pos: False
save_res: True
save_res_vec_name: "../data/preprocessed/GAE_vec.csv"
save_res_cos_name: "../data/preprocessed/GAE_cos.csv"

gae:
  dim: 16
  model: "GAE"

feature_matrix:
  user_num: *user_num
  strength_num: *strength_num
  name_list: *name_list

graph:
  user_num: *user_num
  strength_num: *strength_num
  name_list: *name_list

node2vec:
  embedding_dim: 16
  walk_length: 15
  context_size: 5
  walks_per_node: 40
  num_negative_samples: 1
  q: 6.0
  p: 0.5
  sparse: True
