# GCS
bucket_name: <bucket_name>
base_dir: gs://bucket_name/upload_data/

# base_dir 以下のパス
strengths_path: original/strengths.csv
strengths_bkup_path: original/strengths_bkup.csv
demogra_path: original/demogra.csv
demogra_bkup_path: original/demogra_bkup.csv

top5_path: preprocessed/top5.csv
all34_path: preprocessed/all34.csv
all34_exsits_null_path: preprocessed/all34_exists_null.csv
all34_corr_path: preprocessed/df_corr_all34.csv
res_cos_name_path : preprocessed/GAE_cos.csv

mst_category_path: mst/mst_category.csv
mst_message_json_path: mst/strengths_message.json
colors_strengths_path: mst/dict_colors_strengths.pkl
strengths_desc_path: mst/dict_strengths_desc.pkl

tmp_pdf_save_dir: data/tmp_upload/

departments: ["AN", "BZ", "CO", "DE", "DS", "HR", "MK", "MP", "retiree"]

contact: "********@***.co.jp"

port: 8080