# Change your team name
departments: ["AN", "BZ", "CO", "DE", "DS", "HR", "MK", "MP", "retiree"]

# Change contact
contact_form: "https://docs.google.com/forms/hoge/fuga/embedded=true"

strengths_path: original/strengths.csv
demogra_path: original/demogra.csv

top5_path: preprocessed/top5.csv
all34_path: preprocessed/all34.csv
all34_exsits_null_path: preprocessed/all34_exists_null.csv
all34_corr_path: preprocessed/df_corr_all34.csv
res_cos_name_path : preprocessed/GAE_cos.csv

mst_category_path: mst/mst_category.csv
mst_message_json_path: mst/strengths_message.json
colors_strengths_path: mst/dict_colors_strengths.pkl
strengths_desc_path: mst/dict_strengths_desc.pkl

tmp_pdf_save_dir: data/tmp_upload/

# アクセス可能な IP アドレスを制限する　※制限しない場合は空のリストにする
accepted_ip: []
port: 8080